Repository don9m1n/fastcampus-project-board, pull requests merged in 2023-07, with the labels that each got.

#2 도메인 설계하기
  erd.png
  src/main/java/com/fastcampus/projectboard/domain/Article.java
  src/main/java/com/fastcampus/projectboard/domain/ArticleComment.java
Labels: documentation, enhancement

#5 데이터베이스 접근 로직 테스트 정의
  build.gradle
  erd.png
  src/main/java/com/fastcampus/projectboard/config/JpaConfig.java
  src/main/java/com/fastcampus/projectboard/domain/Article.java
  src/main/java/com/fastcampus/projectboard/domain/ArticleComment.java
  src/main/java/com/fastcampus/projectboard/repository/ArticleCommentRepository.java
  src/main/java/com/fastcampus/projectboard/repository/ArticleRepository.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/java/com/fastcampus/projectboard/repository/JpaRepositoryTest.java
Labels: documentation, enhancement

#8 Auditing 필드 분리
  src/main/java/com/fastcampus/projectboard/domain/Article.java
  src/main/java/com/fastcampus/projectboard/domain/ArticleComment.java
  src/main/java/com/fastcampus/projectboard/domain/BaseEntity.java
Labels: enhancement

#9 게시판 API 만들기
  build.gradle
  src/main/java/com/fastcampus/projectboard/repository/ArticleCommentRepository.java
  src/main/java/com/fastcampus/projectboard/repository/ArticleRepository.java
  src/main/resources/application.yml
  src/test/java/com/fastcampus/projectboard/controller/DataRestTest.java
Labels: documentation, enhancement

#11 게시판 서비스 View 만들기
  build.gradle
  document/erd.png
  erd.png
  src/main/java/com/fastcampus/projectboard/config/SecurityConfig.java
  src/main/java/com/fastcampus/projectboard/controller/ArticleController.java
  src/main/java/com/fastcampus/projectboard/domain/ArticleComment.java
  src/main/java/com/fastcampus/projectboard/domain/BaseEntity.java
  src/main/java/com/fastcampus/projectboard/domain/UserAccount.java
  src/main/java/com/fastcampus/projectboard/repository/ArticleCommentRepository.java
  src/main/java/com/fastcampus/projectboard/repository/ArticleRepository.java
  src/main/java/com/fastcampus/projectboard/repository/UserAccountRepository.java
  src/main/resources/data.sql
  src/main/resources/static/css/bootstrap.min.css
  src/main/resources/static/css/search-bar.css
  src/main/resources/static/js/bootstrap.min.js
  src/main/resources/templates/articles/detail.html
  src/main/resources/templates/articles/index.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/footer.html
  src/main/resources/templates/layout/header.html
  src/test/java/com/fastcampus/projectboard/controller/ArticleControllerTest.java
  src/test/java/com/fastcampus/projectboard/controller/AuthControllerTest.java
  src/test/java/com/fastcampus/projectboard/controller/DataRestTest.java
  src/test/java/com/fastcampus/projectboard/repository/JpaRepositoryTest.java
Labels: documentation, enhancement

#13 게시판 서비스 View 기능 구현 - 테스트까지 작성
  .gitignore
  src/main/java/com/fastcampus/projectboard/controller/MainController.java
  src/main/java/com/fastcampus/projectboard/domain/Article.java
  src/main/java/com/fastcampus/projectboard/domain/ArticleComment.java
  src/main/java/com/fastcampus/projectboard/domain/type/SearchType.java
  src/main/java/com/fastcampus/projectboard/dto/ArticleCommentDto.java
  src/main/java/com/fastcampus/projectboard/dto/ArticleDto.java
  src/main/java/com/fastcampus/projectboard/dto/ArticleWithCommentsDto.java
  src/main/java/com/fastcampus/projectboard/dto/UserAccountDto.java
  src/main/java/com/fastcampus/projectboard/dto/response/ArticleCommentResponse.java
  src/main/java/com/fastcampus/projectboard/dto/response/ArticleResponse.java
  src/main/java/com/fastcampus/projectboard/dto/response/ArticleWithCommentResponse.java
  src/main/java/com/fastcampus/projectboard/repository/ArticleCommentRepository.java
  src/main/java/com/fastcampus/projectboard/repository/ArticleRepository.java
  src/main/java/com/fastcampus/projectboard/service/ArticleCommentService.java
  src/main/java/com/fastcampus/projectboard/service/ArticleService.java
  src/main/resources/data.sql
  src/test/java/com/fastcampus/projectboard/controller/MainControllerTest.java
  src/test/java/com/fastcampus/projectboard/repository/JpaRepositoryTest.java
  src/test/java/com/fastcampus/projectboard/service/ArticleCommentServiceTest.java
  src/test/java/com/fastcampus/projectboard/service/ArticleServiceTest.java
Labels: enhancement

#14 게시판 서비스 View 기능 구현
  src/main/java/com/fastcampus/projectboard/controller/ArticleController.java
  src/main/java/com/fastcampus/projectboard/dto/response/ArticleWithCommentsResponse.java
  src/main/java/com/fastcampus/projectboard/repository/ArticleRepository.java
  src/main/java/com/fastcampus/projectboard/service/ArticleService.java
  src/main/resources/templates/articles/detail.html
  src/main/resources/templates/articles/index.html
  src/test/java/com/fastcampus/projectboard/controller/ArticleControllerTest.java
  src/test/java/com/fastcampus/projectboard/service/ArticleServiceTest.java
Labels: documentation

#15 게시판 서비스 View 기능 구현
  .gitignore
  src/main/java/com/fastcampus/projectboard/controller/ArticleController.java
  src/main/java/com/fastcampus/projectboard/controller/MainController.java
  src/main/java/com/fastcampus/projectboard/domain/Article.java
  src/main/java/com/fastcampus/projectboard/domain/ArticleComment.java
  src/main/java/com/fastcampus/projectboard/domain/type/SearchType.java
  src/main/java/com/fastcampus/projectboard/dto/ArticleCommentDto.java
  src/main/java/com/fastcampus/projectboard/dto/ArticleDto.java
  src/main/java/com/fastcampus/projectboard/dto/ArticleWithCommentsDto.java
  src/main/java/com/fastcampus/projectboard/dto/UserAccountDto.java
  src/main/java/com/fastcampus/projectboard/dto/response/ArticleCommentResponse.java
  src/main/java/com/fastcampus/projectboard/dto/response/ArticleResponse.java
  src/main/java/com/fastcampus/projectboard/dto/response/ArticleWithCommentsResponse.java
  src/main/java/com/fastcampus/projectboard/repository/ArticleCommentRepository.java
  src/main/java/com/fastcampus/projectboard/repository/ArticleRepository.java
  src/main/java/com/fastcampus/projectboard/service/ArticleCommentService.java
  src/main/java/com/fastcampus/projectboard/service/ArticleService.java
  src/main/resources/data.sql
  src/main/resources/templates/articles/detail.html
  src/main/resources/templates/articles/index.html
  src/test/java/com/fastcampus/projectboard/controller/ArticleControllerTest.java
  src/test/java/com/fastcampus/projectboard/controller/MainControllerTest.java
  src/test/java/com/fastcampus/projectboard/repository/JpaRepositoryTest.java
  src/test/java/com/fastcampus/projectboard/service/ArticleCommentServiceTest.java
  src/test/java/com/fastcampus/projectboard/service/ArticleServiceTest.java
Labels: documentation

#17 게시판 페이징 구현
  src/main/java/com/fastcampus/projectboard/controller/ArticleController.java
  src/main/java/com/fastcampus/projectboard/service/PaginationService.java
  src/main/resources/templates/articles/index.html
  src/test/java/com/fastcampus/projectboard/controller/ArticleControllerTest.java
  src/test/java/com/fastcampus/projectboard/service/PaginationServiceTest.java
Labels: enhancement

#19 게시판 페이지 정렬 기능 구현
  src/main/resources/static/css/table-header.css
  src/main/resources/templates/articles/index.html
Labels: enhancement

#23 게시글 검색 기능 구현
  src/main/java/com/fastcampus/projectboard/controller/ArticleController.java
  src/main/java/com/fastcampus/projectboard/domain/type/SearchType.java
  src/main/resources/templates/articles/index.html
  src/test/java/com/fastcampus/projectboard/controller/ArticleControllerTest.java
Labels: enhancement

#24 해시태그 검색 페이지와 기능 구현
  src/main/java/com/fastcampus/projectboard/controller/ArticleController.java
  src/main/java/com/fastcampus/projectboard/repository/ArticleRepository.java
  src/main/java/com/fastcampus/projectboard/repository/querydsl/ArticleRepositoryCustom.java
  src/main/java/com/fastcampus/projectboard/repository/querydsl/ArticleRepositoryCustomImpl.java
  src/main/java/com/fastcampus/projectboard/service/ArticleCommentService.java
  src/main/java/com/fastcampus/projectboard/service/ArticleService.java
  src/main/resources/static/css/article-content.css
  src/main/resources/templates/articles/search-hashtag.html
  src/test/java/com/fastcampus/projectboard/controller/ArticleControllerTest.java
  src/test/java/com/fastcampus/projectboard/controller/AuthControllerTest.java
  src/test/java/com/fastcampus/projectboard/service/ArticleCommentServiceTest.java
  src/test/java/com/fastcampus/projectboard/service/ArticleServiceTest.java
Labels: enhancement

#26 게시글 뷰 기능 구현
  build.gradle
  src/main/java/com/fastcampus/projectboard/controller/ArticleController.java
  src/main/java/com/fastcampus/projectboard/domain/Article.java
  src/main/java/com/fastcampus/projectboard/domain/ArticleComment.java
  src/main/java/com/fastcampus/projectboard/domain/UserAccount.java
  src/main/java/com/fastcampus/projectboard/domain/constant/FormStatus.java
  src/main/java/com/fastcampus/projectboard/domain/constant/SearchType.java
  src/main/java/com/fastcampus/projectboard/dto/ArticleDto.java
  src/main/java/com/fastcampus/projectboard/dto/UserAccountDto.java
  src/main/java/com/fastcampus/projectboard/dto/request/ArticleRequest.java
  src/main/java/com/fastcampus/projectboard/repository/UserAccountRepository.java
  src/main/java/com/fastcampus/projectboard/service/ArticleService.java
  src/main/resources/data.sql
  src/main/resources/templates/articles/detail.html
  src/main/resources/templates/articles/form.html
  src/main/resources/templates/articles/index.html
  src/main/resources/templates/layout/header.html
  src/test/java/com/fastcampus/projectboard/controller/ArticleControllerTest.java
  src/test/java/com/fastcampus/projectboard/service/ArticleCommentServiceTest.java
  src/test/java/com/fastcampus/projectboard/service/ArticleServiceTest.java
  src/test/java/com/fastcampus/projectboard/util/FormDataEncoder.java
  src/test/java/com/fastcampus/projectboard/util/FormDataEncoderTest.java
Labels: enhancement

#27 게시글 댓글 기능 구현
  src/main/java/com/fastcampus/projectboard/controller/ArticleCommentController.java
  src/main/java/com/fastcampus/projectboard/dto/ArticleCommentDto.java
  src/main/java/com/fastcampus/projectboard/dto/request/ArticleCommentRequest.java
  src/main/java/com/fastcampus/projectboard/service/ArticleCommentService.java
  src/main/resources/templates/articles/detail.html
  src/test/java/com/fastcampus/projectboard/controller/ArticleCommentControllerTest.java
  src/test/java/com/fastcampus/projectboard/service/ArticleCommentServiceTest.java
Labels: enhancement

#29 인증 기능 구현
  src/main/java/com/fastcampus/projectboard/config/JpaConfig.java
  src/main/java/com/fastcampus/projectboard/config/SecurityConfig.java
  src/main/java/com/fastcampus/projectboard/controller/ArticleCommentController.java
  src/main/java/com/fastcampus/projectboard/controller/ArticleController.java
  src/main/java/com/fastcampus/projectboard/dto/response/ArticleCommentResponse.java
  src/main/java/com/fastcampus/projectboard/dto/response/ArticleWithCommentsResponse.java
  src/main/java/com/fastcampus/projectboard/dto/security/BoardPrincipal.java
  src/main/java/com/fastcampus/projectboard/repository/ArticleCommentRepository.java
  src/main/java/com/fastcampus/projectboard/repository/ArticleRepository.java
  src/main/java/com/fastcampus/projectboard/service/ArticleCommentService.java
  src/main/java/com/fastcampus/projectboard/service/ArticleService.java
  src/main/resources/data.sql
  src/main/resources/templates/articles/detail.html
  src/main/resources/templates/articles/index.html
  src/main/resources/templates/layout/header.html
  src/test/java/com/fastcampus/projectboard/config/TestSecurityConfig.java
  src/test/java/com/fastcampus/projectboard/controller/ArticleCommentControllerTest.java
  src/test/java/com/fastcampus/projectboard/controller/ArticleControllerTest.java
  src/test/java/com/fastcampus/projectboard/repository/JpaRepositoryTest.java
  src/test/java/com/fastcampus/projectboard/service/ArticleCommentServiceTest.java
  src/test/java/com/fastcampus/projectboard/service/ArticleServiceTest.java
Labels: enhancement
